version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: notes_postgres
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_pass
    ports:
      - "5432:5432"
    volumes:
      - notes_pgdata:/var/lib/postgresql/data

volumes:
  notes_pgdata: